# Generated by Django 4.2.4 on 2025-06-23 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['user__username', 'leaderboard_name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('puuid', models.CharField(max_length=100)),
                ('summonerID', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TftLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('tier', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('lp', models.IntegerField()),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoF.leaderboard')),
                ('player', models.ManyToManyField(related_name='tftleaderboard', to='LoF.player')),
            ],
            options={
                'ordering': ['leaderboard__leaderboard_name', '-tier', '-rank', '-lp'],
            },
        ),
        migrations.CreateModel(
            name='SoloDuoLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('tier', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('lp', models.IntegerField()),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoF.leaderboard')),
                ('player', models.ManyToManyField(related_name='soloduoleaderboard', to='LoF.player')),
            ],
            options={
                'ordering': ['leaderboard__leaderboard_name', '-tier', '-rank', '-lp'],
            },
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='leaderboards', to='LoF.player'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FlexLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('tier', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('lp', models.IntegerField()),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoF.leaderboard')),
                ('player', models.ManyToManyField(related_name='flexleaderboard', to='LoF.player')),
            ],
            options={
                'ordering': ['leaderboard__leaderboard_name', '-tier', '-rank', '-lp'],
            },
        ),
    ]
