# Generated by Django 4.2.4 on 2024-03-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_name', models.CharField(max_length=50, unique=True)),
                ('leaderboard_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('puuid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TftLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('lp', models.IntegerField()),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lof.leaderboard')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tftleaderboard', to='lof.player')),
            ],
        ),
        migrations.CreateModel(
            name='SoloDuoLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('lp', models.IntegerField()),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lof.leaderboard')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soloduoleaderboards', to='lof.player')),
            ],
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='players',
            field=models.ManyToManyField(related_name='leaderboards', to='lof.player'),
        ),
        migrations.CreateModel(
            name='FlexLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('lp', models.IntegerField()),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lof.leaderboard')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flexleaderboard', to='lof.player')),
            ],
        ),
    ]
