# Generated by Django 4.2.4 on 2025-06-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='summonerID',
        ),
    ]
