# Generated by Django 4.2.4 on 2024-03-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lof', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexleaderboard',
            name='player',
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='leaderboards', to='lof.player'),
        ),
        migrations.RemoveField(
            model_name='soloduoleaderboard',
            name='player',
        ),
        migrations.RemoveField(
            model_name='tftleaderboard',
            name='player',
        ),
        migrations.AddField(
            model_name='flexleaderboard',
            name='player',
            field=models.ManyToManyField(related_name='flexleaderboard', to='lof.player'),
        ),
        migrations.AddField(
            model_name='soloduoleaderboard',
            name='player',
            field=models.ManyToManyField(related_name='soloduoleaderboards', to='lof.player'),
        ),
        migrations.AddField(
            model_name='tftleaderboard',
            name='player',
            field=models.ManyToManyField(related_name='tftleaderboard', to='lof.player'),
        ),
    ]
