# Generated by Django 4.2.4 on 2025-06-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoF', '0002_remove_player_summonerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='puuid',
            new_name='lol_puuid',
        ),
        migrations.AddField(
            model_name='player',
            name='tft_puuid',
            field=models.CharField(default='S', max_length=100),
            preserve_default=False,
        ),
    ]
