# Generated by Django 4.2.4 on 2024-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lof', '0002_remove_flexleaderboard_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='region',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='summonerID',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='tag',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
